// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Site_Ilian_DanRaul.Data;

#nullable disable

namespace Site_Ilian_DanRaul.Migrations
{
    [DbContext(typeof(Site_Ilian_DanRaulContext))]
    [Migration("20230112160505_Statut")]
    partial class Statut
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Site_Ilian_DanRaul.Models.ListaAnimecs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DataFinal")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInceput")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Nota")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("StatutID")
                        .HasColumnType("int");

                    b.Property<string>("Titlu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("StatutID");

                    b.ToTable("ListaAnimecs");
                });

            modelBuilder.Entity("Site_Ilian_DanRaul.Models.Statut", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Stare")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Status");
                });

            modelBuilder.Entity("Site_Ilian_DanRaul.Models.ListaAnimecs", b =>
                {
                    b.HasOne("Site_Ilian_DanRaul.Models.Statut", "Statut")
                        .WithMany("ListaAnimeuri")
                        .HasForeignKey("StatutID");

                    b.Navigation("Statut");
                });

            modelBuilder.Entity("Site_Ilian_DanRaul.Models.Statut", b =>
                {
                    b.Navigation("ListaAnimeuri");
                });
#pragma warning restore 612, 618
        }
    }
}
